# Generated by Django 3.2.9 on 2021-11-22 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Laptop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Company', models.CharField(max_length=30)),
                ('Processor', models.CharField(max_length=30)),
                ('Ram', models.IntegerField()),
                ('Price', models.FloatField()),
                ('Del_status', models.CharField(choices=[('Pending', 'Pending'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered')], max_length=30)),
                ('Purchasedate', models.DateField()),
                ('is_paid', models.BooleanField()),
            ],
        ),
    ]
